version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: django/Dockerfile
    image: ${PROJECT_NAME}-django-${DJANGO_PUSH_SERVER_VERSION}
    container_name: ${PROJECT_NAME}-django
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:${DJANGO_SRV_PORT:-8000}"
    # command: gunicorn ./django_push_server/django_push_server.wsgi:application --bind 0.0.0.0:${DJANGO_SRV_PORT:-8000}
    volumes:
      - .:/django_push_server/
    ports:
      - ${DJANGO_SRV_PORT:-8000}:8000
    env_file:
      - .env
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: ${PROJECT_NAME}-nginx-${DJANGO_PUSH_SERVER_VERSION}
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/site-enabled/nginx.conf
      - static_volume:/django_push_server/static
      - media_volume:/django_push_server/media
    environment:
        - NGINX_HOST=${NGINX_HOST:-localhost}
        - NGINX_PORT=${NGINX_PORT:-80}
    ports:
      - ${NGINX_PORT:-80}:80
    depends_on:
      - django
    restart: always

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    image: ${PROJECT_NAME}-webapp-${DJANGO_PUSH_SERVER_VERSION}
    container_name: ${PROJECT_NAME}-webapp
    volumes:
      - ./webapp/:/django_push_server/webapp/
    depends_on:
      - django
    restart: always

volumes:
  static_volume:
  media_volume:
