version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: django/Dockerfile
    image: ${PROJECT_NAME}-django
    container_name: ${PROJECT_NAME}-django
    command: python manage.py runserver 0.0.0.0:${DJANGO_SRV_PORT:-8000}
    ports:
      - ${DJANGO_SRV_PORT:-8000}:8000
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: ${PROJECT_NAME}-nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/site-enabled/nginx.conf
      - static_volume:/django_push_server/static
      - media_volume:/django_push_server/media
    environment:
        - NGINX_HOST=${NGINX_HOST:-localhost}
        - NGINX_PORT=${NGINX_PORT:-80}
    ports:
      - ${NGINX_PORT:-80}:80
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
